package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"

	"github.com/afthaab/job-portal-graphql/graph/model"
)

// CreateSignup is the resolver for the createSignup field.
func (r *mutationResolver) CreateSignup(ctx context.Context, input model.NewUser) (*model.User, error) {
	return r.Svc.UserSignup(input)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
